// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Konnect
{
    /// <summary>
    /// GatewayJWT Resource
    /// </summary>
    [KonnectResourceType("konnect:index/gatewayJwt:GatewayJwt")]
    public partial class GatewayJwt : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Requires replacement if changed. ; must be one of ["HS256", "HS384", "HS512", "RS256", "RS384", "RS512", "ES256", "ES384", "ES512", "PS256", "PS384", "PS512", "EdDSA"]
        /// </summary>
        [Output("algorithm")]
        public Output<string> Algorithm { get; private set; } = null!;

        [Output("consumer")]
        public Output<Outputs.GatewayJwtConsumer> Consumer { get; private set; } = null!;

        /// <summary>
        /// Consumer ID for nested entities. Requires replacement if changed.
        /// </summary>
        [Output("consumerId")]
        public Output<string> ConsumerId { get; private set; } = null!;

        /// <summary>
        /// The UUID of your control plane. This variable is available in the Konnect manager. Requires replacement if changed.
        /// </summary>
        [Output("controlPlaneId")]
        public Output<string> ControlPlaneId { get; private set; } = null!;

        /// <summary>
        /// Unix epoch when the resource was created.
        /// </summary>
        [Output("createdAt")]
        public Output<int> CreatedAt { get; private set; } = null!;

        /// <summary>
        /// Requires replacement if changed.
        /// </summary>
        [Output("key")]
        public Output<string> Key { get; private set; } = null!;

        /// <summary>
        /// Requires replacement if changed.
        /// </summary>
        [Output("rsaPublicKey")]
        public Output<string> RsaPublicKey { get; private set; } = null!;

        /// <summary>
        /// Requires replacement if changed.
        /// </summary>
        [Output("secret")]
        public Output<string> Secret { get; private set; } = null!;

        /// <summary>
        /// Requires replacement if changed.
        /// </summary>
        [Output("tags")]
        public Output<ImmutableArray<string>> Tags { get; private set; } = null!;


        /// <summary>
        /// Create a GatewayJwt resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public GatewayJwt(string name, GatewayJwtArgs args, CustomResourceOptions? options = null)
            : base("konnect:index/gatewayJwt:GatewayJwt", name, args ?? new GatewayJwtArgs(), MakeResourceOptions(options, ""))
        {
        }

        private GatewayJwt(string name, Input<string> id, GatewayJwtState? state = null, CustomResourceOptions? options = null)
            : base("konnect:index/gatewayJwt:GatewayJwt", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing GatewayJwt resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static GatewayJwt Get(string name, Input<string> id, GatewayJwtState? state = null, CustomResourceOptions? options = null)
        {
            return new GatewayJwt(name, id, state, options);
        }
    }

    public sealed class GatewayJwtArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Requires replacement if changed. ; must be one of ["HS256", "HS384", "HS512", "RS256", "RS384", "RS512", "ES256", "ES384", "ES512", "PS256", "PS384", "PS512", "EdDSA"]
        /// </summary>
        [Input("algorithm")]
        public Input<string>? Algorithm { get; set; }

        /// <summary>
        /// Consumer ID for nested entities. Requires replacement if changed.
        /// </summary>
        [Input("consumerId", required: true)]
        public Input<string> ConsumerId { get; set; } = null!;

        /// <summary>
        /// The UUID of your control plane. This variable is available in the Konnect manager. Requires replacement if changed.
        /// </summary>
        [Input("controlPlaneId", required: true)]
        public Input<string> ControlPlaneId { get; set; } = null!;

        /// <summary>
        /// Requires replacement if changed.
        /// </summary>
        [Input("key")]
        public Input<string>? Key { get; set; }

        /// <summary>
        /// Requires replacement if changed.
        /// </summary>
        [Input("rsaPublicKey")]
        public Input<string>? RsaPublicKey { get; set; }

        /// <summary>
        /// Requires replacement if changed.
        /// </summary>
        [Input("secret")]
        public Input<string>? Secret { get; set; }

        [Input("tags")]
        private InputList<string>? _tags;

        /// <summary>
        /// Requires replacement if changed.
        /// </summary>
        public InputList<string> Tags
        {
            get => _tags ?? (_tags = new InputList<string>());
            set => _tags = value;
        }

        public GatewayJwtArgs()
        {
        }
        public static new GatewayJwtArgs Empty => new GatewayJwtArgs();
    }

    public sealed class GatewayJwtState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Requires replacement if changed. ; must be one of ["HS256", "HS384", "HS512", "RS256", "RS384", "RS512", "ES256", "ES384", "ES512", "PS256", "PS384", "PS512", "EdDSA"]
        /// </summary>
        [Input("algorithm")]
        public Input<string>? Algorithm { get; set; }

        [Input("consumer")]
        public Input<Inputs.GatewayJwtConsumerGetArgs>? Consumer { get; set; }

        /// <summary>
        /// Consumer ID for nested entities. Requires replacement if changed.
        /// </summary>
        [Input("consumerId")]
        public Input<string>? ConsumerId { get; set; }

        /// <summary>
        /// The UUID of your control plane. This variable is available in the Konnect manager. Requires replacement if changed.
        /// </summary>
        [Input("controlPlaneId")]
        public Input<string>? ControlPlaneId { get; set; }

        /// <summary>
        /// Unix epoch when the resource was created.
        /// </summary>
        [Input("createdAt")]
        public Input<int>? CreatedAt { get; set; }

        /// <summary>
        /// Requires replacement if changed.
        /// </summary>
        [Input("key")]
        public Input<string>? Key { get; set; }

        /// <summary>
        /// Requires replacement if changed.
        /// </summary>
        [Input("rsaPublicKey")]
        public Input<string>? RsaPublicKey { get; set; }

        /// <summary>
        /// Requires replacement if changed.
        /// </summary>
        [Input("secret")]
        public Input<string>? Secret { get; set; }

        [Input("tags")]
        private InputList<string>? _tags;

        /// <summary>
        /// Requires replacement if changed.
        /// </summary>
        public InputList<string> Tags
        {
            get => _tags ?? (_tags = new InputList<string>());
            set => _tags = value;
        }

        public GatewayJwtState()
        {
        }
        public static new GatewayJwtState Empty => new GatewayJwtState();
    }
}
