// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Konnect
{
    public static class GetGatewayPluginRequestTermination
    {
        public static Task<GetGatewayPluginRequestTerminationResult> InvokeAsync(GetGatewayPluginRequestTerminationArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetGatewayPluginRequestTerminationResult>("konnect:index/getGatewayPluginRequestTermination:getGatewayPluginRequestTermination", args ?? new GetGatewayPluginRequestTerminationArgs(), options.WithDefaults());

        public static Output<GetGatewayPluginRequestTerminationResult> Invoke(GetGatewayPluginRequestTerminationInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetGatewayPluginRequestTerminationResult>("konnect:index/getGatewayPluginRequestTermination:getGatewayPluginRequestTermination", args ?? new GetGatewayPluginRequestTerminationInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetGatewayPluginRequestTerminationArgs : global::Pulumi.InvokeArgs
    {
        [Input("controlPlaneId", required: true)]
        public string ControlPlaneId { get; set; } = null!;

        public GetGatewayPluginRequestTerminationArgs()
        {
        }
        public static new GetGatewayPluginRequestTerminationArgs Empty => new GetGatewayPluginRequestTerminationArgs();
    }

    public sealed class GetGatewayPluginRequestTerminationInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("controlPlaneId", required: true)]
        public Input<string> ControlPlaneId { get; set; } = null!;

        public GetGatewayPluginRequestTerminationInvokeArgs()
        {
        }
        public static new GetGatewayPluginRequestTerminationInvokeArgs Empty => new GetGatewayPluginRequestTerminationInvokeArgs();
    }


    [OutputType]
    public sealed class GetGatewayPluginRequestTerminationResult
    {
        public readonly Outputs.GetGatewayPluginRequestTerminationConfigResult Config;
        public readonly Outputs.GetGatewayPluginRequestTerminationConsumerResult Consumer;
        public readonly Outputs.GetGatewayPluginRequestTerminationConsumerGroupResult ConsumerGroup;
        public readonly string ControlPlaneId;
        public readonly int CreatedAt;
        public readonly bool Enabled;
        public readonly string Id;
        public readonly string InstanceName;
        public readonly ImmutableArray<string> Protocols;
        public readonly Outputs.GetGatewayPluginRequestTerminationRouteResult Route;
        public readonly Outputs.GetGatewayPluginRequestTerminationServiceResult Service;
        public readonly ImmutableArray<string> Tags;
        public readonly int UpdatedAt;

        [OutputConstructor]
        private GetGatewayPluginRequestTerminationResult(
            Outputs.GetGatewayPluginRequestTerminationConfigResult config,

            Outputs.GetGatewayPluginRequestTerminationConsumerResult consumer,

            Outputs.GetGatewayPluginRequestTerminationConsumerGroupResult consumerGroup,

            string controlPlaneId,

            int createdAt,

            bool enabled,

            string id,

            string instanceName,

            ImmutableArray<string> protocols,

            Outputs.GetGatewayPluginRequestTerminationRouteResult route,

            Outputs.GetGatewayPluginRequestTerminationServiceResult service,

            ImmutableArray<string> tags,

            int updatedAt)
        {
            Config = config;
            Consumer = consumer;
            ConsumerGroup = consumerGroup;
            ControlPlaneId = controlPlaneId;
            CreatedAt = createdAt;
            Enabled = enabled;
            Id = id;
            InstanceName = instanceName;
            Protocols = protocols;
            Route = route;
            Service = service;
            Tags = tags;
            UpdatedAt = updatedAt;
        }
    }
}
