// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Konnect
{
    public static class GetGatewayPluginRateLimitingAdvanced
    {
        public static Task<GetGatewayPluginRateLimitingAdvancedResult> InvokeAsync(GetGatewayPluginRateLimitingAdvancedArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetGatewayPluginRateLimitingAdvancedResult>("konnect:index/getGatewayPluginRateLimitingAdvanced:getGatewayPluginRateLimitingAdvanced", args ?? new GetGatewayPluginRateLimitingAdvancedArgs(), options.WithDefaults());

        public static Output<GetGatewayPluginRateLimitingAdvancedResult> Invoke(GetGatewayPluginRateLimitingAdvancedInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetGatewayPluginRateLimitingAdvancedResult>("konnect:index/getGatewayPluginRateLimitingAdvanced:getGatewayPluginRateLimitingAdvanced", args ?? new GetGatewayPluginRateLimitingAdvancedInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetGatewayPluginRateLimitingAdvancedArgs : global::Pulumi.InvokeArgs
    {
        [Input("controlPlaneId", required: true)]
        public string ControlPlaneId { get; set; } = null!;

        public GetGatewayPluginRateLimitingAdvancedArgs()
        {
        }
        public static new GetGatewayPluginRateLimitingAdvancedArgs Empty => new GetGatewayPluginRateLimitingAdvancedArgs();
    }

    public sealed class GetGatewayPluginRateLimitingAdvancedInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("controlPlaneId", required: true)]
        public Input<string> ControlPlaneId { get; set; } = null!;

        public GetGatewayPluginRateLimitingAdvancedInvokeArgs()
        {
        }
        public static new GetGatewayPluginRateLimitingAdvancedInvokeArgs Empty => new GetGatewayPluginRateLimitingAdvancedInvokeArgs();
    }


    [OutputType]
    public sealed class GetGatewayPluginRateLimitingAdvancedResult
    {
        public readonly Outputs.GetGatewayPluginRateLimitingAdvancedConfigResult Config;
        public readonly Outputs.GetGatewayPluginRateLimitingAdvancedConsumerResult Consumer;
        public readonly Outputs.GetGatewayPluginRateLimitingAdvancedConsumerGroupResult ConsumerGroup;
        public readonly string ControlPlaneId;
        public readonly int CreatedAt;
        public readonly bool Enabled;
        public readonly string Id;
        public readonly string InstanceName;
        public readonly ImmutableArray<string> Protocols;
        public readonly Outputs.GetGatewayPluginRateLimitingAdvancedRouteResult Route;
        public readonly Outputs.GetGatewayPluginRateLimitingAdvancedServiceResult Service;
        public readonly ImmutableArray<string> Tags;
        public readonly int UpdatedAt;

        [OutputConstructor]
        private GetGatewayPluginRateLimitingAdvancedResult(
            Outputs.GetGatewayPluginRateLimitingAdvancedConfigResult config,

            Outputs.GetGatewayPluginRateLimitingAdvancedConsumerResult consumer,

            Outputs.GetGatewayPluginRateLimitingAdvancedConsumerGroupResult consumerGroup,

            string controlPlaneId,

            int createdAt,

            bool enabled,

            string id,

            string instanceName,

            ImmutableArray<string> protocols,

            Outputs.GetGatewayPluginRateLimitingAdvancedRouteResult route,

            Outputs.GetGatewayPluginRateLimitingAdvancedServiceResult service,

            ImmutableArray<string> tags,

            int updatedAt)
        {
            Config = config;
            Consumer = consumer;
            ConsumerGroup = consumerGroup;
            ControlPlaneId = controlPlaneId;
            CreatedAt = createdAt;
            Enabled = enabled;
            Id = id;
            InstanceName = instanceName;
            Protocols = protocols;
            Route = route;
            Service = service;
            Tags = tags;
            UpdatedAt = updatedAt;
        }
    }
}
