// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

declare var exports: any;
const __config = new pulumi.Config("konnect");

export declare const konnectAccessToken: string | undefined;
Object.defineProperty(exports, "konnectAccessToken", {
    get() {
        return __config.get("konnectAccessToken");
    },
    enumerable: true,
});

export declare const personalAccessToken: string | undefined;
Object.defineProperty(exports, "personalAccessToken", {
    get() {
        return __config.get("personalAccessToken");
    },
    enumerable: true,
});

/**
 * Server URL (defaults to https://global.api.konghq.com)
 */
export declare const serverUrl: string | undefined;
Object.defineProperty(exports, "serverUrl", {
    get() {
        return __config.get("serverUrl");
    },
    enumerable: true,
});

export declare const systemAccountAccessToken: string | undefined;
Object.defineProperty(exports, "systemAccountAccessToken", {
    get() {
        return __config.get("systemAccountAccessToken");
    },
    enumerable: true,
});

