// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Konnect.Outputs
{

    [OutputType]
    public sealed class ApplicationAuthStrategyOpenidConnect
    {
        /// <summary>
        /// At least one published product version is using this auth strategy.
        /// </summary>
        public readonly bool? Active;
        /// <summary>
        /// JSON-B object containing the configuration for the OIDC strategy. Requires replacement if changed. ; Not Null
        /// </summary>
        public readonly Outputs.ApplicationAuthStrategyOpenidConnectConfigs? Configs;
        /// <summary>
        /// An ISO-8601 timestamp representation of entity creation date.
        /// </summary>
        public readonly string? CreatedAt;
        public readonly Outputs.ApplicationAuthStrategyOpenidConnectDcrProvider? DcrProvider;
        /// <summary>
        /// Requires replacement if changed.
        /// </summary>
        public readonly string? DcrProviderId;
        /// <summary>
        /// The display name of the Auth strategy. This is used to identify the Auth strategy in the Portal UI.
        /// </summary>
        public readonly string? DisplayName;
        /// <summary>
        /// Contains a unique identifier used for this resource.
        /// </summary>
        public readonly string? Id;
        /// <summary>
        /// The name of the auth strategy. This is used to identify the auth strategy in the Konnect UI.
        /// </summary>
        public readonly string? Name;
        /// <summary>
        /// Requires replacement if changed. ; Not Null; must be one of ["openid_connect"]
        /// </summary>
        public readonly string? StrategyType;
        /// <summary>
        /// An ISO-8601 timestamp representation of entity update date.
        /// </summary>
        public readonly string? UpdatedAt;

        [OutputConstructor]
        private ApplicationAuthStrategyOpenidConnect(
            bool? active,

            Outputs.ApplicationAuthStrategyOpenidConnectConfigs? configs,

            string? createdAt,

            Outputs.ApplicationAuthStrategyOpenidConnectDcrProvider? dcrProvider,

            string? dcrProviderId,

            string? displayName,

            string? id,

            string? name,

            string? strategyType,

            string? updatedAt)
        {
            Active = active;
            Configs = configs;
            CreatedAt = createdAt;
            DcrProvider = dcrProvider;
            DcrProviderId = dcrProviderId;
            DisplayName = displayName;
            Id = id;
            Name = name;
            StrategyType = strategyType;
            UpdatedAt = updatedAt;
        }
    }
}
