// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Konnect.Outputs
{

    [OutputType]
    public sealed class GatewayPluginCorsConfig
    {
        /// <summary>
        /// Flag to determine whether the `Access-Control-Allow-Credentials` header should be sent with `true` as the value.
        /// </summary>
        public readonly bool? Credentials;
        /// <summary>
        /// Value for the `Access-Control-Expose-Headers` header. If not specified, no custom headers are exposed.
        /// </summary>
        public readonly ImmutableArray<string> ExposedHeaders;
        /// <summary>
        /// Value for the `Access-Control-Allow-Headers` header.
        /// </summary>
        public readonly ImmutableArray<string> Headers;
        /// <summary>
        /// Indicates how long the results of the preflight request can be cached, in `seconds`.
        /// </summary>
        public readonly double? MaxAge;
        /// <summary>
        /// 'Value for the `Access-Control-Allow-Methods` header. Available options include `GET`, `HEAD`, `PUT`, `PATCH`, `POST`, `DELETE`, `OPTIONS`, `TRACE`, `CONNECT`. By default, all options are allowed.'
        /// </summary>
        public readonly ImmutableArray<string> Methods;
        /// <summary>
        /// List of allowed domains for the `Access-Control-Allow-Origin` header. If you want to allow all origins, add `*` as a single value to this configuration field. The accepted values can either be flat strings or PCRE regexes.
        /// </summary>
        public readonly ImmutableArray<string> Origins;
        /// <summary>
        /// A boolean value that instructs the plugin to proxy the `OPTIONS` preflight request to the Upstream service.
        /// </summary>
        public readonly bool? PreflightContinue;
        /// <summary>
        /// Flag to determine whether the `Access-Control-Allow-Private-Network` header should be sent with `true` as the value.
        /// </summary>
        public readonly bool? PrivateNetwork;

        [OutputConstructor]
        private GatewayPluginCorsConfig(
            bool? credentials,

            ImmutableArray<string> exposedHeaders,

            ImmutableArray<string> headers,

            double? maxAge,

            ImmutableArray<string> methods,

            ImmutableArray<string> origins,

            bool? preflightContinue,

            bool? privateNetwork)
        {
            Credentials = credentials;
            ExposedHeaders = exposedHeaders;
            Headers = headers;
            MaxAge = maxAge;
            Methods = methods;
            Origins = origins;
            PreflightContinue = preflightContinue;
            PrivateNetwork = privateNetwork;
        }
    }
}
