// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Konnect.Outputs
{

    [OutputType]
    public sealed class GatewayControlPlaneProxyUrl
    {
        /// <summary>
        /// Hostname of the proxy URL.
        /// </summary>
        public readonly string Host;
        /// <summary>
        /// Port of the proxy URL.
        /// </summary>
        public readonly int Port;
        /// <summary>
        /// Protocol of the proxy URL.
        /// </summary>
        public readonly string Protocol;

        [OutputConstructor]
        private GatewayControlPlaneProxyUrl(
            string host,

            int port,

            string protocol)
        {
            Host = host;
            Port = port;
            Protocol = protocol;
        }
    }
}
