// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Konnect.Outputs
{

    [OutputType]
    public sealed class GetCloudGatewayConfigurationDataplaneGroupAutoscaleConfigurationDataPlaneGroupAutoscaleAutopilotResult
    {
        /// <summary>
        /// Base number of requests per second that the deployment target should support.
        /// </summary>
        public readonly int BaseRps;
        /// <summary>
        /// must be one of ["autopilot"]
        /// </summary>
        public readonly string Kind;
        /// <summary>
        /// Max number of requests per second that the deployment target should support. If not set, this defaults to 10x base_rps.
        /// </summary>
        public readonly int MaxRps;

        [OutputConstructor]
        private GetCloudGatewayConfigurationDataplaneGroupAutoscaleConfigurationDataPlaneGroupAutoscaleAutopilotResult(
            int baseRps,

            string kind,

            int maxRps)
        {
            BaseRps = baseRps;
            Kind = kind;
            MaxRps = maxRps;
        }
    }
}
