// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Konnect.Outputs
{

    [OutputType]
    public sealed class GetGatewayPluginAclConfigResult
    {
        /// <summary>
        /// Arbitrary group names that are allowed to consume the service or route. One of `config.allow` or `config.deny` must be specified.
        /// </summary>
        public readonly ImmutableArray<string> Allows;
        /// <summary>
        /// Arbitrary group names that are not allowed to consume the service or route. One of `config.allow` or `config.deny` must be specified.
        /// </summary>
        public readonly ImmutableArray<string> Denies;
        /// <summary>
        /// If enabled (`true`), prevents the `X-Consumer-Groups` header from being sent in the request to the upstream service.
        /// </summary>
        public readonly bool HideGroupsHeader;
        public readonly bool IncludeConsumerGroups;

        [OutputConstructor]
        private GetGatewayPluginAclConfigResult(
            ImmutableArray<string> allows,

            ImmutableArray<string> denies,

            bool hideGroupsHeader,

            bool includeConsumerGroups)
        {
            Allows = allows;
            Denies = denies;
            HideGroupsHeader = hideGroupsHeader;
            IncludeConsumerGroups = includeConsumerGroups;
        }
    }
}
