// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package konnect

import (
	"context"
	"reflect"

	"github.com/bunchc/pulumi-tf-provider-konnect/sdk/go/konnect/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupCloudGatewayTransitGateway(ctx *pulumi.Context, args *LookupCloudGatewayTransitGatewayArgs, opts ...pulumi.InvokeOption) (*LookupCloudGatewayTransitGatewayResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupCloudGatewayTransitGatewayResult
	err := ctx.Invoke("konnect:index/getCloudGatewayTransitGateway:getCloudGatewayTransitGateway", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getCloudGatewayTransitGateway.
type LookupCloudGatewayTransitGatewayArgs struct {
	NetworkId string `pulumi:"networkId"`
}

// A collection of values returned by getCloudGatewayTransitGateway.
type LookupCloudGatewayTransitGatewayResult struct {
	CidrBlocks                     []string                                                    `pulumi:"cidrBlocks"`
	CreatedAt                      string                                                      `pulumi:"createdAt"`
	DnsConfigs                     []GetCloudGatewayTransitGatewayDnsConfig                    `pulumi:"dnsConfigs"`
	EntityVersion                  int                                                         `pulumi:"entityVersion"`
	Id                             string                                                      `pulumi:"id"`
	Name                           string                                                      `pulumi:"name"`
	NetworkId                      string                                                      `pulumi:"networkId"`
	State                          string                                                      `pulumi:"state"`
	TransitGatewayAttachmentConfig GetCloudGatewayTransitGatewayTransitGatewayAttachmentConfig `pulumi:"transitGatewayAttachmentConfig"`
	UpdatedAt                      string                                                      `pulumi:"updatedAt"`
}

func LookupCloudGatewayTransitGatewayOutput(ctx *pulumi.Context, args LookupCloudGatewayTransitGatewayOutputArgs, opts ...pulumi.InvokeOption) LookupCloudGatewayTransitGatewayResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupCloudGatewayTransitGatewayResult, error) {
			args := v.(LookupCloudGatewayTransitGatewayArgs)
			r, err := LookupCloudGatewayTransitGateway(ctx, &args, opts...)
			var s LookupCloudGatewayTransitGatewayResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupCloudGatewayTransitGatewayResultOutput)
}

// A collection of arguments for invoking getCloudGatewayTransitGateway.
type LookupCloudGatewayTransitGatewayOutputArgs struct {
	NetworkId pulumi.StringInput `pulumi:"networkId"`
}

func (LookupCloudGatewayTransitGatewayOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupCloudGatewayTransitGatewayArgs)(nil)).Elem()
}

// A collection of values returned by getCloudGatewayTransitGateway.
type LookupCloudGatewayTransitGatewayResultOutput struct{ *pulumi.OutputState }

func (LookupCloudGatewayTransitGatewayResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupCloudGatewayTransitGatewayResult)(nil)).Elem()
}

func (o LookupCloudGatewayTransitGatewayResultOutput) ToLookupCloudGatewayTransitGatewayResultOutput() LookupCloudGatewayTransitGatewayResultOutput {
	return o
}

func (o LookupCloudGatewayTransitGatewayResultOutput) ToLookupCloudGatewayTransitGatewayResultOutputWithContext(ctx context.Context) LookupCloudGatewayTransitGatewayResultOutput {
	return o
}

func (o LookupCloudGatewayTransitGatewayResultOutput) CidrBlocks() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupCloudGatewayTransitGatewayResult) []string { return v.CidrBlocks }).(pulumi.StringArrayOutput)
}

func (o LookupCloudGatewayTransitGatewayResultOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v LookupCloudGatewayTransitGatewayResult) string { return v.CreatedAt }).(pulumi.StringOutput)
}

func (o LookupCloudGatewayTransitGatewayResultOutput) DnsConfigs() GetCloudGatewayTransitGatewayDnsConfigArrayOutput {
	return o.ApplyT(func(v LookupCloudGatewayTransitGatewayResult) []GetCloudGatewayTransitGatewayDnsConfig {
		return v.DnsConfigs
	}).(GetCloudGatewayTransitGatewayDnsConfigArrayOutput)
}

func (o LookupCloudGatewayTransitGatewayResultOutput) EntityVersion() pulumi.IntOutput {
	return o.ApplyT(func(v LookupCloudGatewayTransitGatewayResult) int { return v.EntityVersion }).(pulumi.IntOutput)
}

func (o LookupCloudGatewayTransitGatewayResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupCloudGatewayTransitGatewayResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupCloudGatewayTransitGatewayResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupCloudGatewayTransitGatewayResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupCloudGatewayTransitGatewayResultOutput) NetworkId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupCloudGatewayTransitGatewayResult) string { return v.NetworkId }).(pulumi.StringOutput)
}

func (o LookupCloudGatewayTransitGatewayResultOutput) State() pulumi.StringOutput {
	return o.ApplyT(func(v LookupCloudGatewayTransitGatewayResult) string { return v.State }).(pulumi.StringOutput)
}

func (o LookupCloudGatewayTransitGatewayResultOutput) TransitGatewayAttachmentConfig() GetCloudGatewayTransitGatewayTransitGatewayAttachmentConfigOutput {
	return o.ApplyT(func(v LookupCloudGatewayTransitGatewayResult) GetCloudGatewayTransitGatewayTransitGatewayAttachmentConfig {
		return v.TransitGatewayAttachmentConfig
	}).(GetCloudGatewayTransitGatewayTransitGatewayAttachmentConfigOutput)
}

func (o LookupCloudGatewayTransitGatewayResultOutput) UpdatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v LookupCloudGatewayTransitGatewayResult) string { return v.UpdatedAt }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupCloudGatewayTransitGatewayResultOutput{})
}
