// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package konnect

import (
	"context"
	"reflect"

	"github.com/bunchc/pulumi-tf-provider-konnect/sdk/go/konnect/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupGatewayPluginJwt(ctx *pulumi.Context, args *LookupGatewayPluginJwtArgs, opts ...pulumi.InvokeOption) (*LookupGatewayPluginJwtResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupGatewayPluginJwtResult
	err := ctx.Invoke("konnect:index/getGatewayPluginJwt:getGatewayPluginJwt", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getGatewayPluginJwt.
type LookupGatewayPluginJwtArgs struct {
	ControlPlaneId string `pulumi:"controlPlaneId"`
}

// A collection of values returned by getGatewayPluginJwt.
type LookupGatewayPluginJwtResult struct {
	Config         GetGatewayPluginJwtConfig        `pulumi:"config"`
	Consumer       GetGatewayPluginJwtConsumer      `pulumi:"consumer"`
	ConsumerGroup  GetGatewayPluginJwtConsumerGroup `pulumi:"consumerGroup"`
	ControlPlaneId string                           `pulumi:"controlPlaneId"`
	CreatedAt      int                              `pulumi:"createdAt"`
	Enabled        bool                             `pulumi:"enabled"`
	Id             string                           `pulumi:"id"`
	InstanceName   string                           `pulumi:"instanceName"`
	Protocols      []string                         `pulumi:"protocols"`
	Route          GetGatewayPluginJwtRoute         `pulumi:"route"`
	Service        GetGatewayPluginJwtService       `pulumi:"service"`
	Tags           []string                         `pulumi:"tags"`
	UpdatedAt      int                              `pulumi:"updatedAt"`
}

func LookupGatewayPluginJwtOutput(ctx *pulumi.Context, args LookupGatewayPluginJwtOutputArgs, opts ...pulumi.InvokeOption) LookupGatewayPluginJwtResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupGatewayPluginJwtResult, error) {
			args := v.(LookupGatewayPluginJwtArgs)
			r, err := LookupGatewayPluginJwt(ctx, &args, opts...)
			var s LookupGatewayPluginJwtResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupGatewayPluginJwtResultOutput)
}

// A collection of arguments for invoking getGatewayPluginJwt.
type LookupGatewayPluginJwtOutputArgs struct {
	ControlPlaneId pulumi.StringInput `pulumi:"controlPlaneId"`
}

func (LookupGatewayPluginJwtOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupGatewayPluginJwtArgs)(nil)).Elem()
}

// A collection of values returned by getGatewayPluginJwt.
type LookupGatewayPluginJwtResultOutput struct{ *pulumi.OutputState }

func (LookupGatewayPluginJwtResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupGatewayPluginJwtResult)(nil)).Elem()
}

func (o LookupGatewayPluginJwtResultOutput) ToLookupGatewayPluginJwtResultOutput() LookupGatewayPluginJwtResultOutput {
	return o
}

func (o LookupGatewayPluginJwtResultOutput) ToLookupGatewayPluginJwtResultOutputWithContext(ctx context.Context) LookupGatewayPluginJwtResultOutput {
	return o
}

func (o LookupGatewayPluginJwtResultOutput) Config() GetGatewayPluginJwtConfigOutput {
	return o.ApplyT(func(v LookupGatewayPluginJwtResult) GetGatewayPluginJwtConfig { return v.Config }).(GetGatewayPluginJwtConfigOutput)
}

func (o LookupGatewayPluginJwtResultOutput) Consumer() GetGatewayPluginJwtConsumerOutput {
	return o.ApplyT(func(v LookupGatewayPluginJwtResult) GetGatewayPluginJwtConsumer { return v.Consumer }).(GetGatewayPluginJwtConsumerOutput)
}

func (o LookupGatewayPluginJwtResultOutput) ConsumerGroup() GetGatewayPluginJwtConsumerGroupOutput {
	return o.ApplyT(func(v LookupGatewayPluginJwtResult) GetGatewayPluginJwtConsumerGroup { return v.ConsumerGroup }).(GetGatewayPluginJwtConsumerGroupOutput)
}

func (o LookupGatewayPluginJwtResultOutput) ControlPlaneId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupGatewayPluginJwtResult) string { return v.ControlPlaneId }).(pulumi.StringOutput)
}

func (o LookupGatewayPluginJwtResultOutput) CreatedAt() pulumi.IntOutput {
	return o.ApplyT(func(v LookupGatewayPluginJwtResult) int { return v.CreatedAt }).(pulumi.IntOutput)
}

func (o LookupGatewayPluginJwtResultOutput) Enabled() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupGatewayPluginJwtResult) bool { return v.Enabled }).(pulumi.BoolOutput)
}

func (o LookupGatewayPluginJwtResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupGatewayPluginJwtResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupGatewayPluginJwtResultOutput) InstanceName() pulumi.StringOutput {
	return o.ApplyT(func(v LookupGatewayPluginJwtResult) string { return v.InstanceName }).(pulumi.StringOutput)
}

func (o LookupGatewayPluginJwtResultOutput) Protocols() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupGatewayPluginJwtResult) []string { return v.Protocols }).(pulumi.StringArrayOutput)
}

func (o LookupGatewayPluginJwtResultOutput) Route() GetGatewayPluginJwtRouteOutput {
	return o.ApplyT(func(v LookupGatewayPluginJwtResult) GetGatewayPluginJwtRoute { return v.Route }).(GetGatewayPluginJwtRouteOutput)
}

func (o LookupGatewayPluginJwtResultOutput) Service() GetGatewayPluginJwtServiceOutput {
	return o.ApplyT(func(v LookupGatewayPluginJwtResult) GetGatewayPluginJwtService { return v.Service }).(GetGatewayPluginJwtServiceOutput)
}

func (o LookupGatewayPluginJwtResultOutput) Tags() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupGatewayPluginJwtResult) []string { return v.Tags }).(pulumi.StringArrayOutput)
}

func (o LookupGatewayPluginJwtResultOutput) UpdatedAt() pulumi.IntOutput {
	return o.ApplyT(func(v LookupGatewayPluginJwtResult) int { return v.UpdatedAt }).(pulumi.IntOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupGatewayPluginJwtResultOutput{})
}
