// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package konnect

import (
	"context"
	"reflect"

	"github.com/bunchc/pulumi-tf-provider-konnect/sdk/go/konnect/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupGatewayJwt(ctx *pulumi.Context, args *LookupGatewayJwtArgs, opts ...pulumi.InvokeOption) (*LookupGatewayJwtResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupGatewayJwtResult
	err := ctx.Invoke("konnect:index/getGatewayJwt:getGatewayJwt", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getGatewayJwt.
type LookupGatewayJwtArgs struct {
	ConsumerId     string `pulumi:"consumerId"`
	ControlPlaneId string `pulumi:"controlPlaneId"`
}

// A collection of values returned by getGatewayJwt.
type LookupGatewayJwtResult struct {
	Algorithm      string                `pulumi:"algorithm"`
	Consumer       GetGatewayJwtConsumer `pulumi:"consumer"`
	ConsumerId     string                `pulumi:"consumerId"`
	ControlPlaneId string                `pulumi:"controlPlaneId"`
	CreatedAt      int                   `pulumi:"createdAt"`
	Id             string                `pulumi:"id"`
	Key            string                `pulumi:"key"`
	RsaPublicKey   string                `pulumi:"rsaPublicKey"`
	Secret         string                `pulumi:"secret"`
	Tags           []string              `pulumi:"tags"`
}

func LookupGatewayJwtOutput(ctx *pulumi.Context, args LookupGatewayJwtOutputArgs, opts ...pulumi.InvokeOption) LookupGatewayJwtResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupGatewayJwtResult, error) {
			args := v.(LookupGatewayJwtArgs)
			r, err := LookupGatewayJwt(ctx, &args, opts...)
			var s LookupGatewayJwtResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupGatewayJwtResultOutput)
}

// A collection of arguments for invoking getGatewayJwt.
type LookupGatewayJwtOutputArgs struct {
	ConsumerId     pulumi.StringInput `pulumi:"consumerId"`
	ControlPlaneId pulumi.StringInput `pulumi:"controlPlaneId"`
}

func (LookupGatewayJwtOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupGatewayJwtArgs)(nil)).Elem()
}

// A collection of values returned by getGatewayJwt.
type LookupGatewayJwtResultOutput struct{ *pulumi.OutputState }

func (LookupGatewayJwtResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupGatewayJwtResult)(nil)).Elem()
}

func (o LookupGatewayJwtResultOutput) ToLookupGatewayJwtResultOutput() LookupGatewayJwtResultOutput {
	return o
}

func (o LookupGatewayJwtResultOutput) ToLookupGatewayJwtResultOutputWithContext(ctx context.Context) LookupGatewayJwtResultOutput {
	return o
}

func (o LookupGatewayJwtResultOutput) Algorithm() pulumi.StringOutput {
	return o.ApplyT(func(v LookupGatewayJwtResult) string { return v.Algorithm }).(pulumi.StringOutput)
}

func (o LookupGatewayJwtResultOutput) Consumer() GetGatewayJwtConsumerOutput {
	return o.ApplyT(func(v LookupGatewayJwtResult) GetGatewayJwtConsumer { return v.Consumer }).(GetGatewayJwtConsumerOutput)
}

func (o LookupGatewayJwtResultOutput) ConsumerId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupGatewayJwtResult) string { return v.ConsumerId }).(pulumi.StringOutput)
}

func (o LookupGatewayJwtResultOutput) ControlPlaneId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupGatewayJwtResult) string { return v.ControlPlaneId }).(pulumi.StringOutput)
}

func (o LookupGatewayJwtResultOutput) CreatedAt() pulumi.IntOutput {
	return o.ApplyT(func(v LookupGatewayJwtResult) int { return v.CreatedAt }).(pulumi.IntOutput)
}

func (o LookupGatewayJwtResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupGatewayJwtResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupGatewayJwtResultOutput) Key() pulumi.StringOutput {
	return o.ApplyT(func(v LookupGatewayJwtResult) string { return v.Key }).(pulumi.StringOutput)
}

func (o LookupGatewayJwtResultOutput) RsaPublicKey() pulumi.StringOutput {
	return o.ApplyT(func(v LookupGatewayJwtResult) string { return v.RsaPublicKey }).(pulumi.StringOutput)
}

func (o LookupGatewayJwtResultOutput) Secret() pulumi.StringOutput {
	return o.ApplyT(func(v LookupGatewayJwtResult) string { return v.Secret }).(pulumi.StringOutput)
}

func (o LookupGatewayJwtResultOutput) Tags() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupGatewayJwtResult) []string { return v.Tags }).(pulumi.StringArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupGatewayJwtResultOutput{})
}
