// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package konnect

import (
	"context"
	"reflect"

	"github.com/bunchc/pulumi-tf-provider-konnect/sdk/go/konnect/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupGatewayCustomPluginSchema(ctx *pulumi.Context, args *LookupGatewayCustomPluginSchemaArgs, opts ...pulumi.InvokeOption) (*LookupGatewayCustomPluginSchemaResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupGatewayCustomPluginSchemaResult
	err := ctx.Invoke("konnect:index/getGatewayCustomPluginSchema:getGatewayCustomPluginSchema", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getGatewayCustomPluginSchema.
type LookupGatewayCustomPluginSchemaArgs struct {
	ControlPlaneId string `pulumi:"controlPlaneId"`
	Name           string `pulumi:"name"`
}

// A collection of values returned by getGatewayCustomPluginSchema.
type LookupGatewayCustomPluginSchemaResult struct {
	ControlPlaneId string `pulumi:"controlPlaneId"`
	CreatedAt      int    `pulumi:"createdAt"`
	// The provider-assigned unique ID for this managed resource.
	Id        string `pulumi:"id"`
	LuaSchema string `pulumi:"luaSchema"`
	Name      string `pulumi:"name"`
	UpdatedAt int    `pulumi:"updatedAt"`
}

func LookupGatewayCustomPluginSchemaOutput(ctx *pulumi.Context, args LookupGatewayCustomPluginSchemaOutputArgs, opts ...pulumi.InvokeOption) LookupGatewayCustomPluginSchemaResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupGatewayCustomPluginSchemaResult, error) {
			args := v.(LookupGatewayCustomPluginSchemaArgs)
			r, err := LookupGatewayCustomPluginSchema(ctx, &args, opts...)
			var s LookupGatewayCustomPluginSchemaResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupGatewayCustomPluginSchemaResultOutput)
}

// A collection of arguments for invoking getGatewayCustomPluginSchema.
type LookupGatewayCustomPluginSchemaOutputArgs struct {
	ControlPlaneId pulumi.StringInput `pulumi:"controlPlaneId"`
	Name           pulumi.StringInput `pulumi:"name"`
}

func (LookupGatewayCustomPluginSchemaOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupGatewayCustomPluginSchemaArgs)(nil)).Elem()
}

// A collection of values returned by getGatewayCustomPluginSchema.
type LookupGatewayCustomPluginSchemaResultOutput struct{ *pulumi.OutputState }

func (LookupGatewayCustomPluginSchemaResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupGatewayCustomPluginSchemaResult)(nil)).Elem()
}

func (o LookupGatewayCustomPluginSchemaResultOutput) ToLookupGatewayCustomPluginSchemaResultOutput() LookupGatewayCustomPluginSchemaResultOutput {
	return o
}

func (o LookupGatewayCustomPluginSchemaResultOutput) ToLookupGatewayCustomPluginSchemaResultOutputWithContext(ctx context.Context) LookupGatewayCustomPluginSchemaResultOutput {
	return o
}

func (o LookupGatewayCustomPluginSchemaResultOutput) ControlPlaneId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupGatewayCustomPluginSchemaResult) string { return v.ControlPlaneId }).(pulumi.StringOutput)
}

func (o LookupGatewayCustomPluginSchemaResultOutput) CreatedAt() pulumi.IntOutput {
	return o.ApplyT(func(v LookupGatewayCustomPluginSchemaResult) int { return v.CreatedAt }).(pulumi.IntOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupGatewayCustomPluginSchemaResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupGatewayCustomPluginSchemaResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupGatewayCustomPluginSchemaResultOutput) LuaSchema() pulumi.StringOutput {
	return o.ApplyT(func(v LookupGatewayCustomPluginSchemaResult) string { return v.LuaSchema }).(pulumi.StringOutput)
}

func (o LookupGatewayCustomPluginSchemaResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupGatewayCustomPluginSchemaResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupGatewayCustomPluginSchemaResultOutput) UpdatedAt() pulumi.IntOutput {
	return o.ApplyT(func(v LookupGatewayCustomPluginSchemaResult) int { return v.UpdatedAt }).(pulumi.IntOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupGatewayCustomPluginSchemaResultOutput{})
}
