// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package konnect

import (
	"context"
	"reflect"

	"github.com/bunchc/pulumi-tf-provider-konnect/sdk/go/konnect/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetPortalList(ctx *pulumi.Context, args *GetPortalListArgs, opts ...pulumi.InvokeOption) (*GetPortalListResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetPortalListResult
	err := ctx.Invoke("konnect:index/getPortalList:getPortalList", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getPortalList.
type GetPortalListArgs struct {
	PageNumber *int    `pulumi:"pageNumber"`
	PageSize   *int    `pulumi:"pageSize"`
	Sort       *string `pulumi:"sort"`
}

// A collection of values returned by getPortalList.
type GetPortalListResult struct {
	Datas []GetPortalListData `pulumi:"datas"`
	// The provider-assigned unique ID for this managed resource.
	Id         string            `pulumi:"id"`
	Meta       GetPortalListMeta `pulumi:"meta"`
	PageNumber *int              `pulumi:"pageNumber"`
	PageSize   *int              `pulumi:"pageSize"`
	Sort       *string           `pulumi:"sort"`
}

func GetPortalListOutput(ctx *pulumi.Context, args GetPortalListOutputArgs, opts ...pulumi.InvokeOption) GetPortalListResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetPortalListResult, error) {
			args := v.(GetPortalListArgs)
			r, err := GetPortalList(ctx, &args, opts...)
			var s GetPortalListResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(GetPortalListResultOutput)
}

// A collection of arguments for invoking getPortalList.
type GetPortalListOutputArgs struct {
	PageNumber pulumi.IntPtrInput    `pulumi:"pageNumber"`
	PageSize   pulumi.IntPtrInput    `pulumi:"pageSize"`
	Sort       pulumi.StringPtrInput `pulumi:"sort"`
}

func (GetPortalListOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetPortalListArgs)(nil)).Elem()
}

// A collection of values returned by getPortalList.
type GetPortalListResultOutput struct{ *pulumi.OutputState }

func (GetPortalListResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetPortalListResult)(nil)).Elem()
}

func (o GetPortalListResultOutput) ToGetPortalListResultOutput() GetPortalListResultOutput {
	return o
}

func (o GetPortalListResultOutput) ToGetPortalListResultOutputWithContext(ctx context.Context) GetPortalListResultOutput {
	return o
}

func (o GetPortalListResultOutput) Datas() GetPortalListDataArrayOutput {
	return o.ApplyT(func(v GetPortalListResult) []GetPortalListData { return v.Datas }).(GetPortalListDataArrayOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o GetPortalListResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetPortalListResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetPortalListResultOutput) Meta() GetPortalListMetaOutput {
	return o.ApplyT(func(v GetPortalListResult) GetPortalListMeta { return v.Meta }).(GetPortalListMetaOutput)
}

func (o GetPortalListResultOutput) PageNumber() pulumi.IntPtrOutput {
	return o.ApplyT(func(v GetPortalListResult) *int { return v.PageNumber }).(pulumi.IntPtrOutput)
}

func (o GetPortalListResultOutput) PageSize() pulumi.IntPtrOutput {
	return o.ApplyT(func(v GetPortalListResult) *int { return v.PageSize }).(pulumi.IntPtrOutput)
}

func (o GetPortalListResultOutput) Sort() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetPortalListResult) *string { return v.Sort }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(GetPortalListResultOutput{})
}
