// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Konnect.Inputs
{

    public sealed class GatewayPluginAclConfigArgs : global::Pulumi.ResourceArgs
    {
        [Input("allows")]
        private InputList<string>? _allows;

        /// <summary>
        /// Arbitrary group names that are allowed to consume the service or route. One of `config.allow` or `config.deny` must be specified.
        /// </summary>
        public InputList<string> Allows
        {
            get => _allows ?? (_allows = new InputList<string>());
            set => _allows = value;
        }

        [Input("denies")]
        private InputList<string>? _denies;

        /// <summary>
        /// Arbitrary group names that are not allowed to consume the service or route. One of `config.allow` or `config.deny` must be specified.
        /// </summary>
        public InputList<string> Denies
        {
            get => _denies ?? (_denies = new InputList<string>());
            set => _denies = value;
        }

        /// <summary>
        /// If enabled (`true`), prevents the `X-Consumer-Groups` header from being sent in the request to the upstream service.
        /// </summary>
        [Input("hideGroupsHeader")]
        public Input<bool>? HideGroupsHeader { get; set; }

        [Input("includeConsumerGroups")]
        public Input<bool>? IncludeConsumerGroups { get; set; }

        public GatewayPluginAclConfigArgs()
        {
        }
        public static new GatewayPluginAclConfigArgs Empty => new GatewayPluginAclConfigArgs();
    }
}
