// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Konnect.Inputs
{

    public sealed class GatewayUpstreamHealthchecksPassiveArgs : global::Pulumi.ResourceArgs
    {
        [Input("healthy")]
        public Input<Inputs.GatewayUpstreamHealthchecksPassiveHealthyArgs>? Healthy { get; set; }

        /// <summary>
        /// must be one of ["tcp", "http", "https", "grpc", "grpcs"]
        /// </summary>
        [Input("type")]
        public Input<string>? Type { get; set; }

        [Input("unhealthy")]
        public Input<Inputs.GatewayUpstreamHealthchecksPassiveUnhealthyArgs>? Unhealthy { get; set; }

        public GatewayUpstreamHealthchecksPassiveArgs()
        {
        }
        public static new GatewayUpstreamHealthchecksPassiveArgs Empty => new GatewayUpstreamHealthchecksPassiveArgs();
    }
}
