// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Konnect.Inputs
{

    public sealed class PortalAppearanceCustomThemeColorsTextGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Not Null
        /// </summary>
        [Input("accent")]
        public Input<Inputs.PortalAppearanceCustomThemeColorsTextAccentGetArgs>? Accent { get; set; }

        /// <summary>
        /// Not Null
        /// </summary>
        [Input("footer")]
        public Input<Inputs.PortalAppearanceCustomThemeColorsTextFooterGetArgs>? Footer { get; set; }

        /// <summary>
        /// Not Null
        /// </summary>
        [Input("header")]
        public Input<Inputs.PortalAppearanceCustomThemeColorsTextHeaderGetArgs>? Header { get; set; }

        /// <summary>
        /// Not Null
        /// </summary>
        [Input("headings")]
        public Input<Inputs.PortalAppearanceCustomThemeColorsTextHeadingsGetArgs>? Headings { get; set; }

        /// <summary>
        /// Not Null
        /// </summary>
        [Input("hero")]
        public Input<Inputs.PortalAppearanceCustomThemeColorsTextHeroGetArgs>? Hero { get; set; }

        /// <summary>
        /// Not Null
        /// </summary>
        [Input("link")]
        public Input<Inputs.PortalAppearanceCustomThemeColorsTextLinkGetArgs>? Link { get; set; }

        /// <summary>
        /// Not Null
        /// </summary>
        [Input("primary")]
        public Input<Inputs.PortalAppearanceCustomThemeColorsTextPrimaryGetArgs>? Primary { get; set; }

        /// <summary>
        /// Not Null
        /// </summary>
        [Input("secondary")]
        public Input<Inputs.PortalAppearanceCustomThemeColorsTextSecondaryGetArgs>? Secondary { get; set; }

        public PortalAppearanceCustomThemeColorsTextGetArgs()
        {
        }
        public static new PortalAppearanceCustomThemeColorsTextGetArgs Empty => new PortalAppearanceCustomThemeColorsTextGetArgs();
    }
}
