// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getGatewayHmacAuth(args: GetGatewayHmacAuthArgs, opts?: pulumi.InvokeOptions): Promise<GetGatewayHmacAuthResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("konnect:index/getGatewayHmacAuth:getGatewayHmacAuth", {
        "consumerId": args.consumerId,
        "controlPlaneId": args.controlPlaneId,
    }, opts);
}

/**
 * A collection of arguments for invoking getGatewayHmacAuth.
 */
export interface GetGatewayHmacAuthArgs {
    consumerId: string;
    controlPlaneId: string;
}

/**
 * A collection of values returned by getGatewayHmacAuth.
 */
export interface GetGatewayHmacAuthResult {
    readonly consumer: outputs.GetGatewayHmacAuthConsumer;
    readonly consumerId: string;
    readonly controlPlaneId: string;
    readonly createdAt: number;
    readonly id: string;
    readonly secret: string;
    readonly tags: string[];
    readonly username: string;
}
export function getGatewayHmacAuthOutput(args: GetGatewayHmacAuthOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetGatewayHmacAuthResult> {
    return pulumi.output(args).apply((a: any) => getGatewayHmacAuth(a, opts))
}

/**
 * A collection of arguments for invoking getGatewayHmacAuth.
 */
export interface GetGatewayHmacAuthOutputArgs {
    consumerId: pulumi.Input<string>;
    controlPlaneId: pulumi.Input<string>;
}
