// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getGatewayKeySet(args: GetGatewayKeySetArgs, opts?: pulumi.InvokeOptions): Promise<GetGatewayKeySetResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("konnect:index/getGatewayKeySet:getGatewayKeySet", {
        "controlPlaneId": args.controlPlaneId,
    }, opts);
}

/**
 * A collection of arguments for invoking getGatewayKeySet.
 */
export interface GetGatewayKeySetArgs {
    controlPlaneId: string;
}

/**
 * A collection of values returned by getGatewayKeySet.
 */
export interface GetGatewayKeySetResult {
    readonly controlPlaneId: string;
    readonly createdAt: number;
    readonly id: string;
    readonly name: string;
    readonly tags: string[];
    readonly updatedAt: number;
}
export function getGatewayKeySetOutput(args: GetGatewayKeySetOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetGatewayKeySetResult> {
    return pulumi.output(args).apply((a: any) => getGatewayKeySet(a, opts))
}

/**
 * A collection of arguments for invoking getGatewayKeySet.
 */
export interface GetGatewayKeySetOutputArgs {
    controlPlaneId: pulumi.Input<string>;
}
