// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getGatewayPluginResponseTransformerAdvanced(args: GetGatewayPluginResponseTransformerAdvancedArgs, opts?: pulumi.InvokeOptions): Promise<GetGatewayPluginResponseTransformerAdvancedResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("konnect:index/getGatewayPluginResponseTransformerAdvanced:getGatewayPluginResponseTransformerAdvanced", {
        "controlPlaneId": args.controlPlaneId,
    }, opts);
}

/**
 * A collection of arguments for invoking getGatewayPluginResponseTransformerAdvanced.
 */
export interface GetGatewayPluginResponseTransformerAdvancedArgs {
    controlPlaneId: string;
}

/**
 * A collection of values returned by getGatewayPluginResponseTransformerAdvanced.
 */
export interface GetGatewayPluginResponseTransformerAdvancedResult {
    readonly config: outputs.GetGatewayPluginResponseTransformerAdvancedConfig;
    readonly consumer: outputs.GetGatewayPluginResponseTransformerAdvancedConsumer;
    readonly consumerGroup: outputs.GetGatewayPluginResponseTransformerAdvancedConsumerGroup;
    readonly controlPlaneId: string;
    readonly createdAt: number;
    readonly enabled: boolean;
    readonly id: string;
    readonly instanceName: string;
    readonly protocols: string[];
    readonly route: outputs.GetGatewayPluginResponseTransformerAdvancedRoute;
    readonly service: outputs.GetGatewayPluginResponseTransformerAdvancedService;
    readonly tags: string[];
    readonly updatedAt: number;
}
export function getGatewayPluginResponseTransformerAdvancedOutput(args: GetGatewayPluginResponseTransformerAdvancedOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetGatewayPluginResponseTransformerAdvancedResult> {
    return pulumi.output(args).apply((a: any) => getGatewayPluginResponseTransformerAdvanced(a, opts))
}

/**
 * A collection of arguments for invoking getGatewayPluginResponseTransformerAdvanced.
 */
export interface GetGatewayPluginResponseTransformerAdvancedOutputArgs {
    controlPlaneId: pulumi.Input<string>;
}
