// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getGatewayPluginProxyCache(args: GetGatewayPluginProxyCacheArgs, opts?: pulumi.InvokeOptions): Promise<GetGatewayPluginProxyCacheResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("konnect:index/getGatewayPluginProxyCache:getGatewayPluginProxyCache", {
        "controlPlaneId": args.controlPlaneId,
    }, opts);
}

/**
 * A collection of arguments for invoking getGatewayPluginProxyCache.
 */
export interface GetGatewayPluginProxyCacheArgs {
    controlPlaneId: string;
}

/**
 * A collection of values returned by getGatewayPluginProxyCache.
 */
export interface GetGatewayPluginProxyCacheResult {
    readonly config: outputs.GetGatewayPluginProxyCacheConfig;
    readonly consumer: outputs.GetGatewayPluginProxyCacheConsumer;
    readonly consumerGroup: outputs.GetGatewayPluginProxyCacheConsumerGroup;
    readonly controlPlaneId: string;
    readonly createdAt: number;
    readonly enabled: boolean;
    readonly id: string;
    readonly instanceName: string;
    readonly protocols: string[];
    readonly route: outputs.GetGatewayPluginProxyCacheRoute;
    readonly service: outputs.GetGatewayPluginProxyCacheService;
    readonly tags: string[];
    readonly updatedAt: number;
}
export function getGatewayPluginProxyCacheOutput(args: GetGatewayPluginProxyCacheOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetGatewayPluginProxyCacheResult> {
    return pulumi.output(args).apply((a: any) => getGatewayPluginProxyCache(a, opts))
}

/**
 * A collection of arguments for invoking getGatewayPluginProxyCache.
 */
export interface GetGatewayPluginProxyCacheOutputArgs {
    controlPlaneId: pulumi.Input<string>;
}
